### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by joonkyulol**

### CODE REVIEW

**Comment by OnscreenProton** [comment]
Where is the Linux section?

**Comment by joonkyu** [comment]
> Where is the Linux section?

I don't use Linux, but from my understanding Linux and MacOS generally work the same.

**Comment by lexisother** [comment]
> > Where is the Linux section?
> 
> I don't use Linux, but from my understanding Linux and MacOS generally work the same.

Just add a separate section. The paths don't line up at all on Linux.

**Comment by Kyza** [comment]
If a Linux section is added I will merge this. If you don't know how it would work someone else who does could PR to your fork so the changes show up in this PR.

**Pull request closed without merging**
